// <auto-generated />
using System;
using CitiesManager.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CitiesManager.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.API.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("d2b889d1-5c3e-4b8e-9b8e-1b2b3c4d5e6f"),
                            CityName = "New York"
                        },
                        new
                        {
                            CityId = new Guid("e3c889d1-6d4e-5c8e-9c8e-2b3b4c5d6e7f"),
                            CityName = "Los Angeles"
                        },
                        new
                        {
                            CityId = new Guid("f4d889d1-7e5e-6d9e-9d9e-3b4b5c6d7e8f"),
                            CityName = "Chicago"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
